### ISSUE TITLE
"Update project membership" (adding experiments) leads to 500 Error Page

### ISSUE THREAD

**Issue by adcroft** [jkrasting/dora#5]
Clicking "Add/remove experiments from this project", selecting a few experiments, and then clicking "Update memership", all for an existing project leads to the 500 error page.

**Comment by adcroft** [comment]
Sorry, cut and pasted wrong info. Title and comment updated

**Comment by jkrasting** [comment]
Which experiment did you try to add?  I will see if I can replicate the issue?

**Comment by adcroft** [comment]
CPT. I think it is likely because I needed to edit user permissions first?

**Comment by jkrasting** [comment]
Yes, you need to allow yourself permission to add/edit.  Admin access needs universal privs.

**Comment by adcroft** [comment]
Yes, that works. Close issue? Or do you want to catch this and pop up error message?
